# First we print the list of students
puts "The students of my cohort at Makers Academy"
puts "-------------"
puts "Alex Parkinson"
puts "Carrie Christenson"
puts "Costas Sarris"
puts "Diego Romero"
puts "Erik Griffin"
puts "Gabe Arafa"
puts "Guido Vita Finzi"
puts "Julian Veling"
puts "Kate Beavis"
puts "Kevin Lanzon"
puts "Loris Fochesato"
puts "Louise Beh"
puts "Meads Chalcroft"
puts "Paul Fitz"
puts "Phil Brockwell"
puts "Riz Ali"
puts "Sean Haughton"
puts "Sebastian Pires"
puts "Thomas Strothjohann"
puts "Tom Coakes"
puts "Tommaso Bratto"
puts "Vanessa Virgitti"
puts "Yannick Brunner"
# Finally we print the total
print "Overall, we have "
# It's important that the print() method doesn't add new line characters"
print 23
puts " great students"